version: '3.8'

services:
    test-postgis:
        container_name: test-postgis
        image: postgis/postgis:13-3.1-alpine
        ports:
            - 5432:5432
        expose:
            - 5432
        environment:
            POSTGRES_USER: place
            POSTGRES_PASSWORD: place1234!!
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U place']
            interval: 10s
            timeout: 5s
            retries: 5