version: "3.7"

services:
  postgis:
    container_name: postgis
    image: postgis/postgis:13-3.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: place
      POSTGRES_PASSWORD: place1234!!
